// <auto-generated />
using InvoiceAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvoiceAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250409123338_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InvoiceAPI.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = "4/9/2025",
                            CustomerName = "James Stuart",
                            InvoiceNumber = "0c3f8548-5854-4f02-9f10-b66addf1e42e",
                            Status = 1,
                            TotalAmount = 300m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = "4/9/2025",
                            CustomerName = "John Stones",
                            InvoiceNumber = "ad8f9622-2967-4131-8257-57abdb315edc",
                            Status = 2,
                            TotalAmount = 500m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = "4/9/2025",
                            CustomerName = "Alice Brown",
                            InvoiceNumber = "ddeeb9c3-baf6-42e8-8471-4a5b255381a9",
                            Status = 1,
                            TotalAmount = 750m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = "4/9/2025",
                            CustomerName = "Michael Smith",
                            InvoiceNumber = "4ec794b8-5d6f-49a5-8ca4-327029346239",
                            Status = 2,
                            TotalAmount = 650m
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = "4/9/2025",
                            CustomerName = "Sarah Wilson",
                            InvoiceNumber = "c567a759-eb63-49e9-b9e1-14729e3d13ad",
                            Status = 1,
                            TotalAmount = 200m
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = "4/9/2025",
                            CustomerName = "David Johnson",
                            InvoiceNumber = "e6377e82-c17f-4dd8-963a-376b5c9d12bb",
                            Status = 2,
                            TotalAmount = 1200m
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = "4/9/2025",
                            CustomerName = "Emma Green",
                            InvoiceNumber = "baee2e18-5e90-43ad-b285-83050c12976c",
                            Status = 1,
                            TotalAmount = 450m
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = "4/9/2025",
                            CustomerName = "Oliver Harris",
                            InvoiceNumber = "730bdf49-5c6a-4f4f-8981-7983e6adcea6",
                            Status = 2,
                            TotalAmount = 350m
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = "4/9/2025",
                            CustomerName = "Sophia Adams",
                            InvoiceNumber = "8596a078-e5b9-4712-9237-90303118518b",
                            Status = 1,
                            TotalAmount = 550m
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = "4/9/2025",
                            CustomerName = "Liam Clark",
                            InvoiceNumber = "3f4d654d-2b1a-45df-acc7-462f19cc559e",
                            Status = 2,
                            TotalAmount = 800m
                        });
                });

            modelBuilder.Entity("InvoiceAPI.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("InvoiceAPI.Models.Item", b =>
                {
                    b.HasOne("InvoiceAPI.Models.Invoice", null)
                        .WithMany("Items")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InvoiceAPI.Models.Invoice", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
